apiVersion: v1
kind: ServiceAccount
metadata:
  name: dnstracer
  namespace: dns-tracing
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dnstracer
rules:
- apiGroups: [""]
  resources: ["nodes", "pods"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["events"]
  verbs: ["create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: dnstracer
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: dnstracer
subjects:
- kind: ServiceAccount
  name: dnstracer
  namespace: dns-tracing