// Code generated by bpf2go; DO NOT EDIT.
//go:build arm64

package bpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

// LoadBpfPerfbuf returns the embedded CollectionSpec for BpfPerfbuf.
func LoadBpfPerfbuf() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_BpfPerfbufBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load BpfPerfbuf: %w", err)
	}

	return spec, err
}

// LoadBpfPerfbufObjects loads BpfPerfbuf and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*BpfPerfbufObjects
//	*BpfPerfbufPrograms
//	*BpfPerfbufMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadBpfPerfbufObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := LoadBpfPerfbuf()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// BpfPerfbufSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type BpfPerfbufSpecs struct {
	BpfPerfbufProgramSpecs
	BpfPerfbufMapSpecs
	BpfPerfbufVariableSpecs
}

// BpfPerfbufProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type BpfPerfbufProgramSpecs struct {
	DnsEgress       *ebpf.ProgramSpec `ebpf:"dns_egress"`
	DnsIngress      *ebpf.ProgramSpec `ebpf:"dns_ingress"`
	DnsPacketParser *ebpf.ProgramSpec `ebpf:"dns_packet_parser"`
}

// BpfPerfbufMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type BpfPerfbufMapSpecs struct {
	DnsHeap *ebpf.MapSpec `ebpf:"dns_heap"`
	Events  *ebpf.MapSpec `ebpf:"events"`
}

// BpfPerfbufVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type BpfPerfbufVariableSpecs struct {
	UnusedDns *ebpf.VariableSpec `ebpf:"unused_dns"`
}

// BpfPerfbufObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadBpfPerfbufObjects or ebpf.CollectionSpec.LoadAndAssign.
type BpfPerfbufObjects struct {
	BpfPerfbufPrograms
	BpfPerfbufMaps
	BpfPerfbufVariables
}

func (o *BpfPerfbufObjects) Close() error {
	return _BpfPerfbufClose(
		&o.BpfPerfbufPrograms,
		&o.BpfPerfbufMaps,
	)
}

// BpfPerfbufMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadBpfPerfbufObjects or ebpf.CollectionSpec.LoadAndAssign.
type BpfPerfbufMaps struct {
	DnsHeap *ebpf.Map `ebpf:"dns_heap"`
	Events  *ebpf.Map `ebpf:"events"`
}

func (m *BpfPerfbufMaps) Close() error {
	return _BpfPerfbufClose(
		m.DnsHeap,
		m.Events,
	)
}

// BpfPerfbufVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to LoadBpfPerfbufObjects or ebpf.CollectionSpec.LoadAndAssign.
type BpfPerfbufVariables struct {
	UnusedDns *ebpf.Variable `ebpf:"unused_dns"`
}

// BpfPerfbufPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadBpfPerfbufObjects or ebpf.CollectionSpec.LoadAndAssign.
type BpfPerfbufPrograms struct {
	DnsEgress       *ebpf.Program `ebpf:"dns_egress"`
	DnsIngress      *ebpf.Program `ebpf:"dns_ingress"`
	DnsPacketParser *ebpf.Program `ebpf:"dns_packet_parser"`
}

func (p *BpfPerfbufPrograms) Close() error {
	return _BpfPerfbufClose(
		p.DnsEgress,
		p.DnsIngress,
		p.DnsPacketParser,
	)
}

func _BpfPerfbufClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed bpfperfbuf_arm64_bpfel.o
var _BpfPerfbufBytes []byte
