// Code generated by bpf2go; DO NOT EDIT.
//go:build arm64

package bpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

// LoadBpfRingbuf returns the embedded CollectionSpec for BpfRingbuf.
func LoadBpfRingbuf() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_BpfRingbufBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load BpfRingbuf: %w", err)
	}

	return spec, err
}

// LoadBpfRingbufObjects loads BpfRingbuf and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*BpfRingbufObjects
//	*BpfRingbufPrograms
//	*BpfRingbufMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadBpfRingbufObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := LoadBpfRingbuf()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// BpfRingbufSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type BpfRingbufSpecs struct {
	BpfRingbufProgramSpecs
	BpfRingbufMapSpecs
	BpfRingbufVariableSpecs
}

// BpfRingbufProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type BpfRingbufProgramSpecs struct {
	DnsEgress       *ebpf.ProgramSpec `ebpf:"dns_egress"`
	DnsIngress      *ebpf.ProgramSpec `ebpf:"dns_ingress"`
	DnsPacketParser *ebpf.ProgramSpec `ebpf:"dns_packet_parser"`
}

// BpfRingbufMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type BpfRingbufMapSpecs struct {
	Events *ebpf.MapSpec `ebpf:"events"`
}

// BpfRingbufVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type BpfRingbufVariableSpecs struct {
	UnusedDns *ebpf.VariableSpec `ebpf:"unused_dns"`
}

// BpfRingbufObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadBpfRingbufObjects or ebpf.CollectionSpec.LoadAndAssign.
type BpfRingbufObjects struct {
	BpfRingbufPrograms
	BpfRingbufMaps
	BpfRingbufVariables
}

func (o *BpfRingbufObjects) Close() error {
	return _BpfRingbufClose(
		&o.BpfRingbufPrograms,
		&o.BpfRingbufMaps,
	)
}

// BpfRingbufMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadBpfRingbufObjects or ebpf.CollectionSpec.LoadAndAssign.
type BpfRingbufMaps struct {
	Events *ebpf.Map `ebpf:"events"`
}

func (m *BpfRingbufMaps) Close() error {
	return _BpfRingbufClose(
		m.Events,
	)
}

// BpfRingbufVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to LoadBpfRingbufObjects or ebpf.CollectionSpec.LoadAndAssign.
type BpfRingbufVariables struct {
	UnusedDns *ebpf.Variable `ebpf:"unused_dns"`
}

// BpfRingbufPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadBpfRingbufObjects or ebpf.CollectionSpec.LoadAndAssign.
type BpfRingbufPrograms struct {
	DnsEgress       *ebpf.Program `ebpf:"dns_egress"`
	DnsIngress      *ebpf.Program `ebpf:"dns_ingress"`
	DnsPacketParser *ebpf.Program `ebpf:"dns_packet_parser"`
}

func (p *BpfRingbufPrograms) Close() error {
	return _BpfRingbufClose(
		p.DnsEgress,
		p.DnsIngress,
		p.DnsPacketParser,
	)
}

func _BpfRingbufClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed bpfringbuf_arm64_bpfel.o
var _BpfRingbufBytes []byte
